### ISSUE TITLE
Remove files generated during the build

### ISSUE THREAD

**Issue by jonblack** [cmbi/kmad#36]
Files generated by the build are included in the project. They can be removed. The following list is not exhaustive, check carefully:

- config.h
- config.h.in
- configure

Remember to add these files to `.gitignore` as well.

**Comment by joannalange** [comment]
Isn't config.h.in required for the build though..? When I run the autogen.sh script it throws an error "required file 'config.h.in' not found"

autogen.sh:
`
aclocal && automake --add-missing && autoconf
`

**Comment by jonblack** [comment]
The `AC_CONFIG_HEADERS` macro generates `config.h.in`.

**Comment by joannalange** [comment]
Sorry, I don't get it;) It's the AC_CONFIG_HEADERS macro that throws the error, it needs the 'config.h.in' file to generate the 'config.h' file. Is there something I'm missing?

**Comment by jonblack** [comment]
The top of `config.h.in` has the following:

    /* config.h.in. Generated from configure.ac by autoheader. */

I suspect `AC_CONFIG_HEADERS` calls `autoheader`, but I'm not sure. In any case, the file is definitely generated. Do a `clean`, `dist-clean`, and delete the generate files then go through the compilation process and put the output here and I'll see what I can do.

**Comment by joannalange** [comment]
Thanks for help, had to add autoheader to autogen.sh
